=== BEST-OF-RUN ===
              generation: 0
           subpopulation: 8
                   nodes: 17
                   depth: 3
                    hits: 45
TOP INDIVIDUAL:



-- #1 --
                    hits: 45
             raw fitness: 45.0000
    standardized fitness: 44.0000
        adjusted fitness: 0.5056
TREE:
 (if-food-ahead (if-food-ahead (if-food-ahead move move)
                               (progn3 right left move))
                (progn2 (progn3 right move move)
                        (progn2 left move)))
BEST OF RUN INDIVIDUAL:
   time taken: 400/400
food consumed: 45/89
path: 
     xxxx.xx.......xx...xx.xx........
     ...x..x........x....x..x........
     ...xx.xx.......xx...xx.xxxxx....
     ...#x..x........x....x..#..x.#..
     ...#xx.xx.......xx...xx.#..xxx..
     ...##x#.x####....x...#x......x..
     .....xx.xx..#....xx...xx.....xx.
     ......x..x..#.....x.#..x......x.
     ......xx.xx.#.....xxx..xx.....xx
     .......x..x.#.......x...x....#.x
     x......xx.xx........xx..xx.....x
     x.......x..x#........x...x......
     xx......xx.xx........xx..xx..#..
     .x.......x..x.......#.x...x.....
     .xx......xx.xx......#.xx..xxx...
     ..x.......x..x...#.....x....x...
     ..xx......xx.xx........xx...xx..
     ...x.......x#.x.........x....x..
     ...xx......xx.xxx.......xx...xx.
     ....x.......x...x........x.#..x.
     ....xx......xx..xx.......xx...xx
     .....x......#x..#x........x....x
     x....xx.....#xx..xx.......xx...x
     x.....x.....#.x...x....#...x....
     xx.##.xxxxxx..xxx.xx.......xx...
     .x.........x....x..x........x...
     .xx........xx...xx.xx.......S...
     .#x.....####x##..x..x...........
     .#xx...#....xx...xx.xx..........
     ...x...#.....x....x..x..........
     ..#xxx.......xx...xx.xx.........
     .....x........x....x..x.........
