=== BEST-OF-RUN ===
              generation: 95
           subpopulation: 3
                   nodes: 289
                   depth: 15
                    hits: 1920
TOP INDIVIDUAL:



-- #1 --
                    hits: 1920
             raw fitness: 1920.0000
    standardized fitness: 128.0000
        adjusted fitness: 0.9375
TREE:
 (if (if a0 a0 a0)
     (if (if (if a0 a0 a0)
             (if (if a1 d0 d5)
                 (if a2 d7 d3)
                 (if a1 d0 d5))
             (if d2
                 (if d1 d3 d3) d0))
         (if a0 a0 a0)
         (if a1
             (if a2 d7 d3) d5))
     (if (if a0 d6 a1)
         (if a2 d6
             (if a1 d2 d5))
         (if (if (if a0
                     (if a0 a0 a0)
                     (if (if (if a1 d5 d4) a0 a0) a0 a1))
                 (if (if (if a0 a0 a0)
                         (if d0 a2 d5)
                         (if d2
                             (if d5 d6 d6) d0))
                     (if a2 d7 d3)
                     (if (if (if a2 a1 d3)
                             (if (if a1 d0 d5)
                                 (if a2 d7 d3)
                                 (if a1 d0 d5))
                             (if d2 d4 d0))
                         (if a1
                             (if a2 d7 d3) d5)
                         (if a1
                             (if a2 d7 d3) d5))) a1)
             (if (if a0
                     (if (if a2 a2 d2) a0 a0) a0)
                 (if (if (if a0 a0 a0)
                         (if (if a1 d0 d5)
                             (if a2 d7 d3)
                             (if (if a0 a0 a0)
                                 (if (if (if a2 d7 d3)
                                         (if (if a1 d0 d5)
                                             (if (if a0 a0 a0)
                                                 (if a0
                                                     (if (if d1 a0 d3)
                                                         (if d4 a2 d7)
                                                         (if d5 d2 d6))
                                                     (if d1 d3 d3)) a1)
                                             (if a1 d0 d5)) d7)
                                     (if a0 a0 a0)
                                     (if a1
                                         (if a2 d7 d3) d5))
                                 (if a1 a0 a0)))
                         (if d2 d4 d0)) a0
                     (if (if a1
                             (if (if a0
                                     (if a0 a0 a0)
                                     (if (if (if a1 d5 d4) a0 a0) a0 a1))
                                 (if (if (if a0 a0 a0)
                                         (if d0 a2 d5)
                                         (if d2
                                             (if (if d5 d2 d6) a0 a0) d0))
                                     (if a2 d7 d3)
                                     (if (if (if a2 a1 d3)
                                             (if (if a1 d0 d5)
                                                 (if a2 d7 d3)
                                                 (if a1 d0 d5))
                                             (if d2 d4 d0))
                                         (if a1
                                             (if a2 d7 d3) d5)
                                         (if a1
                                             (if a0 a0 a0) d5))) a1) d5) a0
                         (if (if (if (if a0 a0 a0)
                                     (if d0 a2 d5)
                                     (if d2
                                         (if (if a2 a2 d2) a0 a0) d0))
                                 (if a2 d7 d3)
                                 (if d1 d3 d3)) d4 d0)))
                 (if d2 d4 d0))
             (if (if a1 d1 a2) d4 d0))))
