=== BEST-OF-RUN ===
              generation: 90
           subpopulation: 4
                   nodes: 321
                   depth: 14
                    hits: 1832
TOP INDIVIDUAL:



-- #1 --
                    hits: 1832
             raw fitness: 1832.0000
    standardized fitness: 216.0000
        adjusted fitness: 0.8945
TREE:
 (if (and (and (if (not a2)
                   (not (not (if d6 d6 a1)))
                   (or a0 d2))
               (not (or (not a0)
                        (if (not a2)
                            (and (if a1 a2 d0) d1)
                            (or a0 d2)))))
          (if (if (if (if (or d2 d0)
                          (or (not (and (if (not a2)
                                            (not d0)
                                            (or a0 d2))
                                        (not d4)))
                              (or (if d2 d2 a0)
                                  (or (not a0) a2)))
                          (if d2 d2 a0))
                      (not (if d2 d2 a0))
                      (if (not (or (not a0) a2))
                          (or d4 d0)
                          (or (if a1 d4 a2) d5)))
                  (not (not (or d5 a2)))
                  (not (not (if d6 d6 a1))))
              (if (not a0)
                  (if a2 d0 d6)
                  (or a1 a2))
              (or (not a0)
                  (if (not a2)
                      (not d0)
                      (or a1 a2))))) d3
     (and (or (if (not (or (not a0) a2))
                  (not (and (or (or (or (if d6 d0 a0)
                                        (or d2
                                            (or (not (or a0 d1))
                                                (or (if d2 d2 a0)
                                                    (if (not d1) a1 d5)))))
                                    (and d1 d4)) d5)
                            (if a2 d1 a0)))
                  (or (or (if a0 d7 d2)
                          (not (or (not a0) a2)))
                      (or (and (if a1 a2 d0) d1)
                          (not a1))))
              (and a0 d1))
          (if (or (if (and (not d7)
                           (not (not (and d1 a1))))
                      (or (if (or (and a0 d2)
                                  (and d4 d4)) d4 a1)
                          (or a0 d1))
                      (and d4 d4))
                  (or (or (not (if a1 d4 a2))
                          (or a0 a1))
                      (and d1 a1)))
              (or (or (and (if a2 d4 a1)
                           (if a0 d7 d2))
                      (and (or (and (not (or a1 a2))
                                    (not (if a1 d4 a2))) d5)
                           (or d0 a0)))
                  (or (if (if d4
                              (if (or a1 a2)
                                  (not (or (not a0)
                                           (if (not a2)
                                               (and (if a1 a2 d0) d1)
                                               (or a0 d2)))) d4) d4)
                          (if a2 d4 a1)
                          (if a1 d7 d4))
                      (if (not a0)
                          (if d6 d0 a0)
                          (not (or d5 a2)))))
              (not (or (not (and (if (not a2)
                                     (not d0)
                                     (or a0 d2))
                                 (not d4)))
                       (or (if d2 d2 a0)
                           (if d4 a1
                               (if a1 d4 a2))))))))
